### PR TITLE
Update PushNotification.swift

### PR DESCRIPTION
**Pull request by mayainle**
'UIApplicationLaunchOptionsKey' has been renamed to 'UIApplication.LaunchOptionsKey'

### CODE REVIEW

**Comment by Maxim-Kolmogorov** [comment]
What for?

**Comment by mayainle** [comment]
Didn't compile for me. I got this error:
```
.../Plugins/cordova-plugin-push-notifications/PushNotification.swift:14:110: error: 'UIApplicationLaunchOptionsKey' has been renamed to 'UIApplication.LaunchOptionsKey'
  open override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey : Any]?) -> Bool {
                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                             UIApplication.LaunchOptionsKey
UIKit.UIApplicationLaunchOptionsKey:2:18: note: 'UIApplicationLaunchOptionsKey' was obsoleted in Swift 4.2
public typealias UIApplicationLaunchOptionsKey = UIApplication.LaunchOptionsKey
                 ^
Command EmitSwiftModule failed with a nonzero exit code

error: emit-module command failed with exit code 1 (use -v to see invocation)
```

I checked xcode and got the hint to replace it and after that it compiled. 
Maybe I misunderstood or missed something, if so please reject the PR.

**Comment by Maxim-Kolmogorov** [comment]
I will check. Can u tell me which is version cordova u use?

**Comment by mayainle** [comment]
Cordova version is 11.0.0
ios platform version is 6.2.0
xcode 13.3.1

Thank you

**Comment by Maxim-Kolmogorov** [comment]
Maybe another version of Xcode has created this error (I have 13.2) or maybe another version of cordova (I have 10)... I don't know. I have applied your code and plugin still works. It is cool. I will conduct another test today, and if i don't get any errors, i will apply pr and update npm package.

**Comment by mayainle** [comment]
Yeah probably. Cool, thank you!

**Pull request merged**
